export const Data = [
    {
        id: 1,
        title: "This is a title",
        status: "todo", 
        image: "https://d3nn873nee648n.cloudfront.net/900x600/16909/13-SM734012.jpg",
        date: "Feb 23",
        attach: 5,       
    },
    {
        id: 2,
        title: "This is a title",
        status: "todo", 
        image: "",
        date: "Feb 23",
        attach: 5,       
    },
    {
        id: 5,
        title: "This is a title",
        status: "doing", 
        image: "",   
        date: "Feb 23",
        attach: 5,    
    },
    {
        id: 6,
        title: "This is a title",
        status: "doing", 
        image: "https://d3nn873nee648n.cloudfront.net/900x600/2341/20-SM105669.jpg", 
        date: "Feb 23",
        attach: 5,      
    },
    {
        id: 7,
        title: "This is a title",
        status: "doing", 
        image: "",    
        date: "Feb 23",
        attach: 5,   
    },
    {
        id: 9,
        title: "This is a title",
        status: "done", 
        image: "",    
        date: "Feb 23",
        attach: 5,   
    },
    {
        id: 10,
        title: "This is a title",
        status: "done", 
        image: "",    
        date: "Feb 23",
        attach: 5,   
    },
    {
        id: 11,
        title: "This is a title",
        status: "done", 
        image: "https://d3nn873nee648n.cloudfront.net/900x600/18648/220-SM848863.jpg",    
        date: "Feb 23",
        attach: 5,   
    },
    {
        id: 13,
        title: "This is a title",
        status: "resources", 
        image: "https://d3nn873nee648n.cloudfront.net/900x600/20362/12-SM1020557.jpg",  
        date: "Feb 23",
        attach: 5,     
    },
    {
        id: 14,
        title: "This is a title",
        status: "resources", 
        image: "",  
        date: "Feb 23",
        attach: 5,     
    }
]